### PR TITLE
[semver:patch] Usage example update

### LINKED ISSUE #185: Should throw error on missing SLACK_ACCESS_TOKEN
## Orb version:

4.0.0

## What happened:

Notify job passes but no notification is sent.

## Expected behavior:

Notification sent successfully.

## Additional Information:

I had forgotten to set the SLACK_ACCESS_TOKEN environment variable. Was quite surprised when I realized that the issue was the missing env var and no error had been produced.

### LINKED ISSUE #200: Unclear event values
In examples provided in https://circleci.com/developer/orbs/orb/circleci/slack#usage-successful_tagged_deployment,

event key is associated to 'success, while the Orb description indicates values can be one of 'pass', 'fail' and 'always'.

Which one is correct between 'pass' and 'success?'

### PR DESCRIPTION
**Pull request by KyleTryon**
Fixes #200 - Incorrect parameter value for event.
Fixes #185 - Improved error messaging for missing required values.

### CODE REVIEW

**Comment by KyleTryon** [comment]
Looking for other tiny items to add to this patch.

**Comment by KyleTryon** [comment]
Fixes #185

File: src/scripts/notify.sh [hunk 1]
```diff
@@ -111,11 +106,29 @@ BranchFilter() {
...
+        echo "Please note, Webhooks are no longer used for the Slack Orb (v4 +)."
+        echo "Follow the setup guide available in the wiki: https://github.com/CircleCI-Public/slack-orb/wiki/Setup"
+    fi
+}
+
 # Will not run if sourced from another script.
 # This is done so this script may be tested.
 ORB_TEST_ENV="bats-core"
 if [ "${0#*$ORB_TEST_ENV}" = "$0" ]; then
-    . "/tmp/SLACK_JOB_STATUS"
```
Comment (KyleTryon) [inline src/scripts/notify.sh:118]: CC @gmemstr I think this may be from the old orb as the blame shows you added this, but it was during the major re-write. Im testing now removing this. Do you have any idea what this might have been? Looks to be sourcing a tmp file that I wouldnt expect to exist. I think it was possibly used in the old orb, not sure how I didnt see it.

Comment (gmemstr) [reply src/scripts/notify.sh:118]: I don't recall removing/adding `. "/tmp/SLACK_JOB_STATUS"`, so I don't really know :(

**Review by gmemstr — APPROVED** [review]

File: src/scripts/notify.sh (hunk 1 above)
Comment (skyeagle) [reply src/scripts/notify.sh:118]: Looks like this has been referenced for carrying over the job's status and removing this introduced a bug.

I see this output, but not sure where it comes from:

*Slack - Detecting Job Status (FAIL)*
```
echo 'export CCI_STATUS="fail"' > /tmp/SLACK_JOB_STATUS
```

Specifying `event: fail` stopped working for us.

Comment (KyleTryon) [reply src/scripts/notify.sh:118]: Ahh it was hidden in the other command / run step of course 🤦 very sorry about that. Patching this now

Comment (KyleTryon) [reply src/scripts/notify.sh:118]: Thank you @skyeagle
